### ISSUE TITLE
Grafika

### ISSUE THREAD

**Issue by Spera97** [matf-pp/2023_Pesak#1]
- [x] kontura oblika i velicine cetke koja prati poziciju kursora

- [x] graficki interfejs za:
> - [x] izbor materiajala
> - [x] pauziranje, resetovanje, nastavljanje simulacije
> - [x] izbor oblika cetke (krug/kvadrat)
> - [x] cuvanje i ucitavanje celog platna u i iz nekog zgodnog fajla npr json

- [x] cuvanje i ucitavanje celog platna u i iz nekog zgodnog fajla npr json

**Comment by Spera97** [comment]
само пребаци четку у кружну и доста

**Comment by sajberk** [comment]
rešeno šefe, sad imaš obe
