### ISSUE TITLE
Code comments

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp/2023_Pesak#11]
Maybe we should clean up some of the [comments](https://github.com/matf-pp/2023_Pesak/blob/66a9b2d4a6be87da094c213c71151ec0bada6354/main.go#LL24C38-L24C38) so GitHub copilot does not learn Serbian swears as a side-effect? 

[wontfix?]

**Comment by lukastan** [comment]
The swears were not up to the usual standard, so I removed them. Fixed.
