### ISSUE TITLE
const

### ISSUE THREAD

**Issue by Spera97** [matf-pp/2023_Pesak#14]
мислим да имамо много var ствари које би могле бити const, ја то до сада нисам мењао јер смо причали о требљењу мапа али пошто видим да тога неће бити можда треба нешто урадити поводом овога

**Comment by sajberk** [comment]
Trebljenja mapa će apsolutno biti + zašto ti smeta da stvari ostanu var + nisam siguran da si u pravu + kakve to veze ima sa mapama

**Comment by lukastan** [comment]
@sajberk + ratio

**Comment by Spera97** [comment]
нешто нешто добра пракса
мапе су те које су већински вар, њихов садржај се неће мењати у рантајму него се само учитавати у низ
дакле не требимо их само их ни не користимо током симулације
нису га волели,,,, јер га нису разумели,,,,,,,,,,,,
