### ISSUE TITLE
obojCesticu undefined in brushLib.go

### ISSUE THREAD

**Issue by LCEnzo** [matf-pp/2023_Pesak#15]
I pulled the latest changes, and now I can't build the program. I tried with a new clone, and got the same error.

Terminal output:
❯ pwd
/home/qcerris-user/Desktop/2023_Pesak
❯ git status
On branch main
Your branch is up-to-date with 'origin/main'.

nothing to commit, working tree clean
❯ git pull
Already up-to-date.
❯ go version
go version go1.20.4 linux/amd64
❯ go build
\# main/src/brushPack
src/brushPack/brushLib.go:81:6: undefined: obojCesticu
src/brushPack/brushLib.go:91:7: undefined: obojCesticu
src/brushPack/brushLib.go:110:6: undefined: obrisiCesticu
src/brushPack/brushLib.go:120:7: undefined: obrisiCesticu

**Comment by lukastan** [comment]
Sorry for late response, the commit was meant to change the README but somehow I changed obojCesticu to ObojCesticu too without thinking. Everything works fine now.
