### ISSUE TITLE
Hardware rendering

### ISSUE THREAD

**Issue by sajberk** [matf-pp/2023_Pesak#2]
pesak mnogo sporo pada kada ga ima puno jer je kompletno cpu rendered. trenutni difolt (240x144, 4 piksela po čestici) je skroz ok i fps mi ostaje preko 60 čak i kada se napuni ekran, ali to je baš smešno mala rezolucija. već na 400x300 na skoro praznom ekranu dobijam oko 30 fpsa, a na 800x600, sa jednom česticom po pikselu fps bleji ispod 10 od početka. na 1080p pesku imam 2 frejma po sekundi, i mislim da je to bizarno. mislim da bi hardware accelerated pesak radio dosta brže, ali za to su potrebne male promene kojima ću se pozabaviti malo kasnije u posebnom branchu ako bude bilo vremena. mislite li da nam je potreban brži pesak koji se renderuje preko grafe ili je to gubljenje vremena? 

pros: kursor nam više neće treperiti i pesak će verovatno raditi mnogo brže
cons: potrošiću vreme koje bih inače proveo gledajući crtaće

hardver korišćen za testiranje: i7 6700hq

**Comment by sajberk** [comment]
da, samo sam želeo da napravim issue ali dodaću fps counter u narednom commitu. nz da li želimo da bude na ekranu ako se pritisne neko dugmence ili ne?

**Comment by lukastan** [comment]
Izgleda da će nam ovo ubrzo postati problem, tako da nije na odmet da se uradi. Šta misliš da npr ako je 4 piksela po čestici strečujemo platno 4 puta u širinu i visinu? Da li je to uopšte moguće?

**Comment by sajberk** [comment]
@lukastan zapravo mislim da to već radimo i da juče samo nisam imao pojma šta pričam

**Comment by lukastan** [comment]
(nisam ni ja siguran, bolje da pitamo Speru)

**Comment by Spera97** [comment]
да да мени се чини да то радимо то је она var brojPikselaPoCestici или како се већ зове 😅
што се фпс бројача тиче ја лично мислим да би било кул да нека акција активира причљиви кој у неком ћошку приказује рецимо фпс, материјал температуру и тикер челије на којој је тренутно центриран миш или назив гумба уколико је миш преко неког од њих
@sajberk размисли је л те то не би мрзело ја мислим да би било баш епски


додао бих да мислим да би то било јако корисно за нас током дибаговања

**Comment by sajberk** [comment]
kul sada imamo sve spomenuto osim normalnog renderovanja B)

 moj profajler kaže da nam 50% vremena odlazi na FillRect tkd ćemo to definitivno probati da sredimo za koji dan

**Comment by sajberk** [comment]
zdravo svima, od komita b445be51463fa7308f3ed2f33b44faf9a6570552 više nemamo ovaj problem
živeli!
