### ISSUE TITLE
Navigacija - tj. desna strana prozora

### ISSUE THREAD

**Issue by lukastan** [matf-pp/2023_Pesak#3]
- [x] #4
    - [x] dugmić za normalni mod gledanja platna (trenutno se aktivira na N)
    - [x] dugmić za temperaturni mod gledanja platna (trenutno se aktivira na T)
    - [x] dugmić za gustinski mod gledanja platna (trenutno se aktivira na D)
- [x] hover iznad dugmića koji objašnjava za šta su
- [x] dva reda za materijale
- [x] separacija dugmića koji služe za izbor materijala, dela koji je za pauziranje, ???, brisanje i dela koji je za biranje modova (eventualno sadrži i dugme za importovanje/outportovanje slika)

**Comment by sajberk** [comment]
ne sviđa mi se, skinuo sam ti admina

**Comment by Spera97** [comment]
колега како радио гумб може садржати три опције радимо на класичним рачунарима а не релативистичким 

што се објашњења гумбова тиче о томе сам тачно писао причајући о причљивом моду [овде](https://github.com/matf-pp/2023_Pesak/issues/2)

**Comment by Spera97** [comment]
чини ми се да имамо све, затварам
