### ISSUE TITLE
ко ми је ставио бубу у супи

### ISSUE THREAD

**Issue by Spera97** [matf-pp/2023_Pesak#5]
[Screencast from 04-27-2023 07:28:58 AM.webm](https://user-images.githubusercontent.com/35925344/234768430-d159fa56-3289-4803-970e-826538f29562.webm)
Имамо један баг кој нисам у стању да нађем већ једно три комита заредом а ради се о томе да када нешто гушће пада кроз нешто ређе нпр камен кроз лаву (симулација температуре угашена при тестирању) честице камена постају честице лаве. Молим колегу Луку да баци поглед можда га нађе свежим очима.

степс то реплицате:

- на врх updateTemp ф-је додај `buffer[i][j].Temperatura = matrix[i][j].Temperatura; return;`
- закоментариши цео `if (astanje & 0b0100) != 0` део унутар updatePosition ф-је
- исто и са `if (astanje & 0b0010) != 0` делом, довољно је само вертикално кретање
- направи гомилицу лаве на дну екрана
- направи блок камена над њом
- гледај како се при контакту претвара у лаву из неког разлога 
- ??????
- профит

**Comment by sajberk** [comment]
je l se ne ugreje samo kamen jako brzo i postane lava? msm da se to nije dešavalo sa npr vodom koja je svakako ređa od lave

**Comment by lukastan** [comment]
Možda popravljem, molim dotične da provere kad budu u stanju za to.

**Comment by Spera97** [comment]
@sajberk а краљу јеси ли порчитао шта сам написао буквално угасим температуру

**Comment by Spera97** [comment]
океј колега Лука је предложио нешто што не да поправља баг (заправо га не поправља) него потпуно револуционизује наш приступ итерацијама и апдејтовању целог канваса тако да затварам овај ишју иде гас будућност је данас

**Comment by Spera97** [comment]
добро мислим баг је сада у потпуности заобиђен можда није јасно из претходног коментара
