### ISSUE TITLE
ukloniti sve do poslednje heš mape iz peska

### ISSUE THREAD

**Issue by sajberk** [matf-pp/2023_Pesak#6]
moj profajler kaže da nam 15% vremena odlazi na pristup heš mapama i one će morati da hodaju po dasci. javite mi kad to rešite.

- [ ] heš mape su iskorenjene

**Comment by Spera97** [comment]
ајде прво рилис сада кад смо без иједног нама познатог бага по први пут од када је пјеска и вјека па онда да средимо те мапице

**Comment by sajberk** [comment]
btw ako imamo fanove koji redovno čitaju naše komentare u kodu i diskusije na githabu, nakon sređivanja procesa renderovanja je procenat vremena koji odlazi na pristup heš mapama od po ~10 elemenata otišao na >30% tkd ovo rešavamo večeras sleš sutra. sve najbolje i hvala vam što se interesujete za pesak.

**Comment by Spera97** [comment]
одличан посао краљу
