### ISSUE TITLE
операција: прометеј

### ISSUE THREAD

**Issue by Spera97** [matf-pp/2023_Pesak#7]
ја мислим да би било баш епски да до 30. априла убацимо ватру и дрво и неке биљчице можда
@lukastan желиш ли то ти макар ватру да јој даш онај твој флатер или да ја то завршим рецимо сутра поподне?

**Comment by lukastan** [comment]
Uh oh

**Comment by Spera97** [comment]
што се мене тиче ово је готово, што се траве тиче није журба
